---
name: Formatting Workflow

# yamllint disable-line rule:truthy
on:
  - pull_request
  - push

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install NPM dependencies
        run: npm ci

      - name: Run Prettier formatter
        run: npx prettier --check --config ./.prettierrc .
